// products
export const GET_PRODUCTS = 'GET_PRODUCTS'
export const PRODUCTS_FETCHING = 'PRODUCTS_FETCHING'
export const ADD_PRESCRIBED_PRODUCT = 'ADD_PRESCRIBED_PRODUCT'
export const DELETE_PRESCRIBED_PRODUCT = 'DELETE_PRESCRIBED_PRODUCT'
export const UPDATE_PRESCRIBED_PRODUCT = 'UPDATE_PRESCRIBED_PRODUCT'
export const SET_QR_CODE = 'SET_QR_CODE'
export const POST_PRESCRIPTION = 'POST_PRESCRIPTION'