// products
export const GET_PRODUCTS = 'GET_PRODUCTS'
export const PRODUCTS_FETCHING = 'PRODUCTS_FETCHING'
export const ADD_PRESCRIBED_PRODUCT = 'ADD_PRESCRIBED_PRODUCT'
export const DELETE_PRESCRIBED_PRODUCT = 'DELETE_PRESCRIBED_PRODUCT'
